function unetTest(NameValueArgs)
arguments 
    NameValueArgs.Optimizer (1, 1) {mustBeTextScalar} = "adam" % "sgdm", "rmsprop", "adam", "lbfgs", "lm"
    NameValueArgs.LearnRate (1, 1) {mustBeNumeric} = 1e-3   % Default = 1e-2
    NameValueArgs.MaxEpochs (1, 1) {mustBeGreaterThan(NameValueArgs.MaxEpochs, 0)} = 1      % Number of Epochs to Run
    NameValueArgs.BatchSize (1, 1) {mustBeGreaterThan(NameValueArgs.BatchSize, 0)} = 4      % Minibatch Size
    NameValueArgs.LearnSchedule (1, 1) {mustBeTextScalar} = "piecewise"
    NameValueArgs.LearnDropFactor (1, 1) {mustBePositive} = 0.2
    NameValueArgs.LearnDropPeriod (1, 1) {mustBePositive} = 5
    NameValueArgs.Momentum (1, 1) {mustBePositive, mustBeNumeric} = 0.9 % "sgdm" only
    NameValueArgs.EncoderDepth (1, 1) {mustBePositive} = 4
    NameValueArgs.NumFirstEncoderFilters (1, 1) {mustBePositive, mustBeNumeric} = 64
    NameValueArgs.FilterSize (1, 1) {mustBePositive, mustBeNumeric} = 3
    NameValueArgs.GradientDecay (1, 1) {mustBePositive, mustBeNumeric} = 0.9 % adam only
    NameValueArgs.SquaredGradient (1, 1) {mustBePositive, mustBeNumeric} = 0.999 % adam only
    NameValueArgs.Epsilon (1, 1) {mustBePositive, mustBeNumeric} = 1e-8 % adam only
    NameValueArgs.L2 (1, 1) {mustBePositive, mustBeNumeric} = 0.0001 % adam only
    NameValueArgs.GradientThreshold (1, 1) {mustBePositive, mustBeNumeric} = 1 % adam only
    NameValueArgs.GradientThresholdMethod (1, :) {mustBeTextScalar}= "l2norm" % adam only
end

fprintf("Script Start: %s\n", datetime('now','TimeZone','local','Format','d-MMM-y HH:mm:ss Z'));

trainImagePath = fullfile('Images', 'Training');
testImagePath = fullfile("Images", "Evaluation");
pixelImagePath = fullfile("Images", "GroundTruth");

classNames = [ "Signal", "Noise" ];         % labels
pixelLabelIDs = { [0 0 255], [255 0 0] }; % create an array that maps pixels to classes
imageSize = [ 720 960 ];
class_dim = size(pixelLabelIDs, 2);

function classes = componentMatrixToClasses(componentMatrix)
    [ ~, classes ] = max(componentMatrix, [], 3);
end

if NameValueArgs.Optimizer == "adam"
    parameters = sprintf("%s-%f-%d-%d-%s-%f-%d-%d-%02d-%d-%f-%03f-%10f-%05f-%d-%s", ...
                     NameValueArgs.Optimizer, ...
                     NameValueArgs.LearnRate, ...
                     NameValueArgs.MaxEpochs, ...
                     NameValueArgs.BatchSize, ...
                     NameValueArgs.LearnSchedule, ...
                     NameValueArgs.LearnDropFactor, ...
                     NameValueArgs.LearnDropPeriod, ...
                     NameValueArgs.EncoderDepth, ...
                     NameValueArgs.NumFirstEncoderFilters, ...
                     NameValueArgs.FilterSize, ...
                     NameValueArgs.GradientDecay, ...
                     NameValueArgs.SquaredGradient, ...
                     NameValueArgs.Epsilon, ...
                     NameValueArgs.L2, ...
                     NameValueArgs.GradientThreshold, ...
                     NameValueArgs.GradientThresholdMethod);
else
    parameters = sprintf("%s-%f-%d-%d-%s-%d-%d-%f-%d-%02d-%d", ...
                     NameValueArgs.Optimizer, ...
                     NameValueArgs.LearnRate, ...
                     NameValueArgs.MaxEpochs, ...
                     NameValueArgs.BatchSize, ...
                     NameValueArgs.LearnSchedule, ...
                     NameValueArgs.LearnDropFactor, ...
                     NameValueArgs.LearnDropPeriod, ...
                     NameValueArgs.Momentum, ...
                     NameValueArgs.EncoderDepth, ...
                     NameValueArgs.NumFirstEncoderFilters, ...
                     NameValueArgs.FilterSize);
end
fldrArgs = struct("TrainImages",  trainImagePath, ...
                  "LabelImages",  pixelImagePath, ...
                  "OutputFolder", sprintf("UNet-%s", parameters), ...
                  "ModelFile",    sprintf("trainnet-%s.mat", parameters));

disp([ 'Directory: ' fldrArgs.OutputFolder ]);
if exist(fldrArgs.OutputFolder, "dir") ~= 7
    mkdir(fldrArgs.OutputFolder);
end

generate_test_images(testImagePath, imageSize);
generate_training_images(imageSize);
generate_pixel_labels(trainImagePath, pixelImagePath, pixelLabelIDs, imageSize, @componentMatrixToClasses);
% generate_evaluation_truth(); % TODO: Pass in necessary parameters
if NameValueArgs.Optimizer == "adam"
    trainParams = struct("Optimizer", NameValueArgs.Optimizer, ...
                         "LearnRate", NameValueArgs.LearnRate, ...
                         "MaxEpochs", NameValueArgs.MaxEpochs, ...
                         "Minibatch", NameValueArgs.BatchSize, ...
                         "LearnSche", NameValueArgs.LearnSchedule, ...
                         "LearnDrop", NameValueArgs.LearnDropFactor, ...
                         "LDropPerd", NameValueArgs.LearnDropPeriod, ...
                         "EncdrDpth", NameValueArgs.EncoderDepth, ...
                         "NumFilters", NameValueArgs.NumFirstEncoderFilters, ...
                         "FilterSize", NameValueArgs.FilterSize, ...
                         "GradientDecay", NameValueArgs.GradientDecay, ...
                         "SquaredGradient", NameValueArgs.SquaredGradient, ...
                         "Epsilon", NameValueArgs.Epsilon, ...
                         "L2", NameValueArgs.L2, ...
                         "GradientThreshold", NameValueArgs.GradientThreshold, ...
                         "GradientThresholdMethod", NameValueArgs.GradientThresholdMethod);
else
    trainParams = struct("Optimizer", NameValueArgs.Optimizer, ...
                         "LearnRate", NameValueArgs.LearnRate, ...
                         "MaxEpochs", NameValueArgs.MaxEpochs, ...
                         "Minibatch", NameValueArgs.BatchSize, ...
                         "LearnSche", NameValueArgs.LearnSchedule, ...
                         "LearnDrop", NameValueArgs.LearnDropFactor, ...
                         "LDropPerd", NameValueArgs.LearnDropPeriod, ...
                         "Momentum", NameValueArgs.Momentum, ...
                         "EncdrDpth", NameValueArgs.EncoderDepth, ...
                         "NumFilters", NameValueArgs.NumFirstEncoderFilters, ...
                         "FilterSize", NameValueArgs.FilterSize);
end
train_network(fldrArgs, imageSize, classNames, pixelLabelIDs, trainParams); % train the neural network and save to disk (only call once per concat)

netTrained = load(fullfile(fldrArgs.OutputFolder, fldrArgs.ModelFile));
test_network(testImagePath, imageSize, netTrained.netTrained, fldrArgs.OutputFolder); % load the neural network from disk and then test the data
gen_predictive_img(testImagePath, fldrArgs.OutputFolder, imageSize, classNames);

end
